/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface Option1 {
  name: string
}
export interface Option2 {
  name: string
}
export interface Input {
  option1?: Option1 | undefined | null
  option2?: Array<Option2> | undefined | null
}
export interface Option1String {
  name: string
}
export interface Option2String {
  name: string
}
export interface InputString {
  option1?: Option1String | undefined | null
  option2?: Array<Option2String> | undefined | null
}
export function transform(option: Input): Input
export function transformWithString(option: InputString): InputString
